signtool.exe not found

diff --git a/.github/workflows/windows-distribution.yml b/.github/workflows/windows-distribution.yml
--- a/.github/workflows/windows-distribution.yml
+++ b/.github/workflows/windows-distribution.yml
@@ -65,22 +65,32 @@ jobs:
       - name: Locate signtool.exe
         id: locate_signtool
         run: |
-          $signtoolPath = where signtool.exe
+          $signtoolPath = (Get-Command signtool.exe -ErrorAction SilentlyContinue).Source
+          if (-not $signtoolPath) {
+            $signtoolPath = Get-ChildItem -Path "C:\Program Files (x86)\Windows Kits\10\bin" -Recurse -Filter signtool.exe -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName -First 1
+          }
+          if (-not $signtoolPath) {
+            $signtoolPath = Get-ChildItem -Path "C:\Program Files\Windows Kits\10\bin" -Recurse -Filter signtool.exe -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName -First 1
+          }
+          if (-not $signtoolPath) {
+            Write-Error "signtool.exe not found"
+            exit 1
+          }
           echo "signtool.exe path: $signtoolPath"
           echo "SIGNSIGNTOOL_PATH=$signtoolPath" >> $env:GITHUB_ENV
+        shell: pwsh
+
+      - name: List Program Files
+        run: dir "C:\Program Files (x86)\Windows Kits\10\bin\x64\ucrt"
+        shell: pwsh
+
+      - name: List Program Files
+        run: dir "C:\Program Files (x86)\Windows Kits\10\bin"
         shell: pwsh
 
       # Windows - Msi
       - name: Build Windows Release
         run: ./gradlew packageReleaseMsi
-
-      - name: List Program Files
-        run: dir "C:\Program Files (x86)\Windows Kits\10\bin\x64"
-        shell: pwsh
-
-      - name: List Program Files
-        run: dir "C:\Program Files (x86)\Windows Kits\"
-        shell: pwsh
 
       - name: Move and rename MSI file
         run: |
